USE EL_TMAIOZ_School;
-- create Teachers table
CREATE TABLE TEACHERS (
TEACH_ID INT PRIMARY KEY,
TEACH_NAME VARCHAR(225),
DOB DATE ,
TEACH_GENDER VARCHAR(225),
TEACH_EMAIL VARCHAR(225),
OFFICE_NUM INT 
);
